apiVersion: v1
kind: ReplicationController
metadata:
  name: flaskapp-replication
spec:
  replicas: 2
  selector:
    app: flaskapp
  template:
    metadata:
      name: flaskapp
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskapp
        image: jsmn3/cloud-assignment2:latest
        ports:
        - containerPort: 5000
